# Generated by Django 4.1.3 on 2023-03-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tokens_access_remove_tokens_refresh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokens',
            old_name='access_token',
            new_name='accesstoken',
        ),
        migrations.RenameField(
            model_name='tokens',
            old_name='refresh_token',
            new_name='refreshtoken',
        ),
    ]
