# Generated by Django 4.1.3 on 2023-03-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_access_token_tokens_accesstoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
