# Generated by Django 4.1.3 on 2023-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tokens_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('userid', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
