# Generated by Django 4.1.3 on 2023-03-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='code',
        ),
    ]
