# Generated by Django 4.1.3 on 2023-03-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userData',
        ),
        migrations.RemoveField(
            model_name='zoomuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='zoomuser',
            name='type',
        ),
        migrations.AddField(
            model_name='zoomuser',
            name='userid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
