# Generated by Django 4.1.3 on 2023-03-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_userdata_remove_zoomuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='zoomuser',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zoomuser',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
