# Generated by Django 4.1.3 on 2023-03-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_zoomuser_email_alter_zoomuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createmeeting',
            name='agenda',
        ),
    ]
