# Generated by Django 4.1.3 on 2023-03-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_createmeeting_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createmeeting',
            name='user',
        ),
    ]
